version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Restaurant-Rating"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lys9d22mgc9g"
s3_prefix = "Restaurant-Rating"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []